import 'package:better_learn_programming/models/language-model.dart';

final List<CategoryTopic> categoryTile = [
  CategoryTopic(
    id: 1,
    name: 'C++',
    imagePath: 'images/c.png',
    topic1: 'Basics',
    topic2: 'Syntax',
    topic3: 'Data Types',
    topic4: 'Conditions',
    topic5: 'Loops',
    topic6: 'Function',
    topic7: 'Array',
    topic8: 'Extras',
    topic9: 'String',
    topic10: 'OOP',
  ),
  CategoryTopic(
    id: 2,
    name: 'Java',
    imagePath: 'images/java.png',
    topic1: 'Basics',
    topic2: 'Syntax',
    topic3: 'Data Types',
    topic4: 'Conditions',
    topic5: 'Loops',
    topic6: 'Function',
    topic7: 'Array',
    topic8: 'Extras',
    topic9: 'String',
    topic10: 'OOP',
  ),
  CategoryTopic(
    id: 3,
    name: 'Python',
    imagePath: 'images/python.png',
    topic1: 'Basics',
    topic2: 'Syntax',
    topic3: 'Data Types',
    topic4: 'Conditions',
    topic5: 'Loops',
    topic6: 'Function',
    topic7: 'Array',
    topic8: 'Extras',
    topic9: 'String',
    topic10: 'OOP',
  ),
  CategoryTopic(
    id: 6,
    name: 'JavaScript',
    imagePath: 'images/js-format.png',
    topic1: 'Basics',
    topic2: 'Syntax',
    topic3: 'Data Types',
    topic4: 'Conditions',
    topic5: 'Loops',
    topic6: 'Function',
    topic7: 'Array',
    topic8: 'Extras',
    topic9: 'String',
    topic10: 'OOP',
  ),
];
